[programs.localnet]
msp = "MSPdQo5ZdrPh6rU1LsvUv5nRhAnj1mj6YQEqBUq8YwZ"

[programs.devnet]
msp = "MSPdQo5ZdrPh6rU1LsvUv5nRhAnj1mj6YQEqBUq8YwZ"

[programs.mainnet]
msp = "MSPCUMbLfy2MeT6geLMMzrUkv1Tx88XRApaVRdyxTuu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/msp*.ts"
