name: cd-sdks

on:
  push:
    branches:
      - main

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release & Publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3      
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd sdks/msp && yarn install
      - run: cd sdks/msp && yarn build

      - name: Meandao Release & Publish Toolkit
        uses: mean-dao/npm-publish-toolkit@v17
        with:
          access: public
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gchat_webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          path: ./sdks/msp
