name: CD SDKs

on:
  push:
    branches:
      - main
    paths:
      - 'sdks/msp/**.js'
      - 'sdks/msp/**.ts'
      - 'sdks/msp/package.json'
      - 'sdks/msp/tsconfig.json'

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: "Release & Publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd sdks/msp && yarn install
      - run: cd sdks/msp && yarn build

      - name: Publish package to NPM
        uses: ./.github/actions/gh-release-and-npm-publish
        with:
          access: public
          release-type: prerelease
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # gchat_webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          path: ./sdks/msp
