name: Programs CI

on:
  pull_request:
    branches:    
      - main
    paths:
      - 'programs/msp/**.rs'
      - 'programs/Cargo.toml'
      - 'tests/**.ts'
      - 'Anchor.toml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
  workflow_dispatch:

env:
  SOLANA_VERSION: "1.13.4"
  ANCHOR_VERSION: "0.24.2"
  RUST_TOOLCHAIN: "stable"
  NODE_VERSION: "16"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana-anchor
      with:
            solana-cli-version: ${{ env.SOLANA_VERSION }}
            anchor-cli-version: ${{ env.ANCHOR_VERSION }}
            rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
            node-version: ${{ env.NODE_VERSION }}
            solana-default-keypair: ${{ secrets.DEVNET_PAYER_KEY }}

      # Run build
      - name: Cache build
        uses: Swatinem/rust-cache@v1

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [build]
    environment:
        name: localnet
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana-anchor

      # Rust Unit tests
      - name: Run Cargo Tests
        run: cargo test-bpf -- --nocapture

      # Run tests
      - name: Run Anchor Tests
        run: anchor test --provider.cluster localnet --provider.wallet ~/.config/solana/id.json -- --features test

  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: [tests]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Sec3 Pro Audit
        id: sec3-scan
        continue-on-error: true    # set to true if you don't want to fail jobs
        uses: sec3dev/pro-action@v1
        with:
          path: programs/msp
          sec3-token: ${{ secrets.SEC3_AUTO_AUDITOR_TOKEN }}
      - name: Upload Sarif Report
        continue-on-error: true    # set to true if you don't want to fail jobs
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sec3-report.sarif
      - name: Check on failures
        if: steps.sec3-scan.outcome != 'success'
        run: exit 1
