name: Programs Deploy Devnet

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'programs/msp/**.rs'
      - 'programs/msp/Cargo.toml'
      - 'tests/**.ts'
      - 'Anchor.toml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'deploy.devnet.sh'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
  workflow_dispatch:

env:
  SOLANA_VERSION: '1.18.20'
  ANCHOR_VERSION: '0.24.2'
  RUST_TOOLCHAIN: 'stable'
  NODE_VERSION: '20'
  PROGRAM_NAME: 'msp'
  MINIMUM_SOL_NEEDED: 6
  BUILD_NUMBER: $GITHUB_RUN_NUMBER

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana-anchor
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}
          anchor-cli-version: ${{ env.ANCHOR_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
          node-version: ${{ env.NODE_VERSION }}
          solana-default-keypair: ${{ secrets.DEVNET_PAYER_KEY }}

      # Run build
      - name: Build program
        run: cargo build
      # - name: Run clippy
      #   run: cargo clippy -- -D warnings -A clippy::too_many_arguments

  audit:
    name: Audit
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Sec3 Pro Audit
        id: sec3-scan
        continue-on-error: true # set to true if you don't want to fail jobs
        uses: sec3dev/pro-action@v1
        with:
          path: programs/msp
          sec3-token: ${{ secrets.SEC3_TOKEN }}
      - name: Upload Sarif Report
        continue-on-error: true # set to true if you don't want to fail jobs
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sec3-report.sarif
      - name: Check on failures
        if: steps.sec3-scan.outcome != 'success'
        run: exit 1

  deploy-devnet:
    name: Deploy devnet
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [audit]
    environment:
      name: devnet
    env:
      CLUSTER: 'devnet'
      RPC_URL: ${{ secrets.DEVNET_RPC_URL }}
      MULTISIG_AUTHORITY_ADDRESS: ${{ secrets.DEVNET_MULTISIG_AUTHORITY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana-anchor
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}
          anchor-cli-version: ${{ env.ANCHOR_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
          node-version: ${{ env.NODE_VERSION }}
          solana-default-keypair: ${{ secrets.DEVNET_PAYER_KEY }}

      # Deploy with 3 retry
      - name: Deploy program
        uses: nick-fields/retry@v2
        with:
          retry_wait_seconds: 2
          timeout_minutes: 10
          retry_on: error
          max_attempts: 3
          command: ./deploy.devnet.sh

      # Print outputs
      - name: Print buffer account
        run: |
          echo ${{ env.BUFFER_ACCOUNT_URL }}
          echo '### New Program Buffer Account! :rocket:' >> $GITHUB_STEP_SUMMARY
          echo "[${{ env.BUFFER_ACCOUNT_ADDRESS }}](${{ env.BUFFER_ACCOUNT_URL }})" >> $GITHUB_STEP_SUMMARY
