name: SDKs Pre-release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'sdks/payment-streaming/**.js'
      - 'sdks/payment-streaming/**.ts'
      - 'sdks/payment-streaming/package.json'
      - 'sdks/payment-streaming/tsconfig.json'
      - 'sdks/payment-streaming/yarn.lock'
      - 'sdks/payment-streaming/run-tests.sh'

jobs:
  pre-release:
    if: github.event.pull_request.merged == true
    name: "Pre-release & Publish Beta (on PR merged)"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Release & Publish to NPM
        uses: ./.github/actions/gh-release-and-npm-publish
        with:
          access: public
          release-type: prerelease
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # gchat_webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          path: ./sdks/payment-streaming
          tag_prefix: sdk-
