name: SDKs CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'sdks/payment-streaming/**.js'
      - 'sdks/payment-streaming/**.ts'
      - 'sdks/payment-streaming/package.json'
      - 'sdks/payment-streaming/tsconfig.json'
      - 'sdks/payment-streaming/yarn.lock'
      - 'sdks/payment-streaming/run-tests.sh'

env:
  SOLANA_VERSION: "1.13.4"
  ANCHOR_VERSION: "0.24.2"
  RUST_TOOLCHAIN: "stable"
  NODE_VERSION: "16"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana-anchor
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}
          anchor-cli-version: ${{ env.ANCHOR_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
          node-version: ${{ env.NODE_VERSION }}
          solana-default-keypair: ${{ secrets.DEVNET_PAYER_KEY }}
      - run: cd sdks/payment-streaming && yarn install
      - run: cd sdks/payment-streaming && yarn build
  sonar-scan:
    name: "Sonar Scan"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.verbose=false
            -Dsonar.projectKey=payment-streaming-sdk
            -Dsonar.sources=sdks/payment-streaming/src/
  run-sdk-tests:
    name: Run SDK tests
    needs: [sonar-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana-anchor
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}
          anchor-cli-version: ${{ env.ANCHOR_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
          node-version: ${{ env.NODE_VERSION }}
          solana-default-keypair: ${{ secrets.DEVNET_PAYER_KEY }}
      - run: cd sdks/payment-streaming && ./run-tests.sh
        name: Run Tests
