name: SDKs Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'one of: major, minor, patch, prerelease'
        required: true

jobs:
  release:
    name: "Release & Publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: GH Release & Publish to NPM
        uses: ./.github/actions/gh-release-and-npm-publish
        with:
          access: public
          release-type: ${{ inputs.release-type }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # gchat_webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          path: ./sdks/payment-streaming
          tag_prefix: sdk-
